Set up github to build and publish python packages | chore(release)
microsoft/onnx-script pull request #570
Opened 2023-03-28 18:02 UTC by liqunfu

2023-03-28 20:20 UTC, justinchuby requested changes
We should not make pyproject changes because it is the recommended way of configuring new Python projects

2023-03-29 00:25 UTC, justinchuby commented on .github/workflows/release.yml
> +        twine upload --verbose onnx-script/dist/*.whl --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TESTPYPI_USERNAME }} -p ${{ secrets.TESTPYPI_PASSWORD }}
```suggestion
```

I don't think we need test pypi. ONNX is moving away from it too

2023-03-29 00:26 UTC, justinchuby commented on .github/workflows/release.yml
> +        twine upload --verbose onnx-script/dist/*.whl --repository-url https://upload.pypi.org/legacy/ -u ${{ secrets.ONNXSCRIPTWEEKLY_USERNAME }} -p ${{ secrets.ONNXSCRIPTWEEKLY_TOKEN }}
Consider using pypa's official task:

https://github.com/justinchuby/lintrunner-adapters/blob/7a3a7b409db1d2146ef98f56a3406930e8270dbd/.github/workflows/ci.yml#L116-L119

2023-03-29 00:27 UTC, justinchuby commented on .github/workflows/release.yml
> +        cd onnx-script
Does this test the wheel or the source?

2023-03-29 00:27 UTC, justinchuby commented on .github/workflows/release.yml
> +        Get-ChildItem -Path dist/*.whl | foreach {python -m pip install --upgrade $_.fullname}
Prefer linux. It's faster and we don't need to write powershell

2023-03-29 00:28 UTC, justinchuby commented on .github/workflows/release.yml
> +          python setup.py bdist_wheel
Create a conditional step? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif

2023-03-29 00:29 UTC, justinchuby commented on .github/workflows/release.yml
> +        }
I don't think we need to build for different architectures. In fact I think we only need to create one universal build?

2023-03-29 00:29 UTC, justinchuby commented on .github/workflows/release.yml
> +        architecture: ['x64', 'x86']
```suggestion
```

I think we just need one

2023-03-29 00:30 UTC, justinchuby commented on .github/workflows/release.yml
> +
```suggestion
```

2023-03-29 00:33 UTC, justinchuby commented on pyproject.toml
> -build-backend = "setuptools.build_meta"
These can stay

2023-03-29 00:33 UTC, justinchuby commented on pyproject.toml
> -onnx = ["py.typed"]
I think these should stay too

2023-03-29 00:33 UTC, justinchuby commented on setup.py
> +from collections import namedtuple
```suggestion
```

2023-03-29 00:34 UTC, justinchuby commented on setup.py
> +from datetime import date
Import modules only: `import datetime` and use `datetime.date`

2023-03-29 00:34 UTC, justinchuby commented on setup.py
> +PACKAGE_NAME = "onnx_script"
```suggestion
PACKAGE_NAME = "onnx-script"
```

2023-03-29 00:35 UTC, justinchuby commented on setup.py
> +packages = setuptools.find_packages() + setuptools.find_namespace_packages(
```suggestion
```

2023-03-29 00:35 UTC, justinchuby commented on setup.py
> +
```suggestion
```

2023-03-29 00:35 UTC, justinchuby commented on setup.py
> +    packages=packages,
```suggestion
```

2023-03-29 00:38 UTC, justinchuby commented on noxfile.py
> -    session.run("python", "-m", "build")
I prefer this continue to work. We should not drop `python -m build` support as it is the new/right way to build.

2023-03-29 00:38 UTC, justinchuby commented on noxfile.py
> -    session.run("python", "-m", "build")
Having

```

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
```

below should enable support for this

2023-03-29 00:38 UTC, justinchuby commented on .github/workflows/release.yml
> +         path: ./onnx-script
Is there a reason why we clone to a sub folder?

2023-03-29 00:39 UTC, justinchuby commented on .github/workflows/release.yml
> +      shell: bash
```suggestion
```
nit

2023-03-29 00:39 UTC, justinchuby commented on .github/workflows/release.yml
> +         git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
```suggestion
```

we don't have submodules

2023-03-29 00:41 UTC, justinchuby commented on setup.py
> +
nit: This is done by pyproject.toml. Anything that doesn't need to happen in setup.py shouldn't happen in it imo.

2023-04-03 16:49 UTC, justinchuby commented on .github/workflows/release.yml
> +    branches: [main, rel-*]
Do we not want to create release branch?

2023-04-03 16:57 UTC, jcwchen commented on .github/workflows/release.yml
> +    branches: [main, rel-*]
Ah good catch. I didn't see any now, but it makes sense we should have them.

2023-04-03 23:17 UTC, justinchuby commented
We need to exclude opgen

![image](https://user-images.githubusercontent.com/11205048/229646867-74f62eb1-e2a2-4438-91a2-53adbfcfc27e.png)

2023-04-03 23:19 UTC, justinchuby commented
Looks like the version in metadata is not dev
![image](https://user-images.githubusercontent.com/11205048/229647064-20e146c7-bcb2-49d4-a923-5c670b35ac51.png)

2023-04-04 02:08 UTC, justinchuby approved these changes

2023-04-04 02:45 UTC, merged

2023-04-04 16:57 UTC, justinchuby commented on .github/workflows/main.yaml
> +    if: (github.event_name == 'schedule') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v'))
Need to complete the if by adding that from release